"""integration_status_and_unrecognised_chat

Revision ID: 351992e58560
Revises: f2a97224a48b
Create Date: 2026-08-31 12:56:06.373338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351992e58560'
down_revision = 'f2a97224a48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unrecognised_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=80), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'chat_id', name='uq_unrecognised_chat')
    )
    with op.batch_alter_table('unrecognised_chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unrecognised_chat_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unrecognised_chat_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.drop_column('last_attempted_at')
        batch_op.drop_column('last_error')
        batch_op.drop_column('last_status')

    with op.batch_alter_table('unrecognised_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unrecognised_chat_project_id'))
        batch_op.drop_index(batch_op.f('ix_unrecognised_chat_chat_id'))

    op.drop_table('unrecognised_chat')
    # ### end Alembic commands ###
