"""content_template_description

Revision ID: dac2cc7ee310
Revises: 351992e58560
Create Date: 2026-08-31 19:58:29.472964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac2cc7ee310'
down_revision = '351992e58560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_template', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
