"""baseline

Revision ID: f2a97224a48b
Revises: 
Create Date: 2026-08-31 12:49:51.686955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a97224a48b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('accent', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organisation_slug'), ['slug'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('community_scope', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organisation_id', name='uq_membership')
    )
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_user_id'), ['user_id'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('support_url', sa.String(length=500), nullable=True),
    sa.Column('telegram_bot_token_enc', sa.Text(), nullable=True),
    sa.Column('telegram_bot_username', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('agent_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('tone', sa.String(length=120), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('preferred_terms', sa.Text(), nullable=True),
    sa.Column('forbidden_terms', sa.Text(), nullable=True),
    sa.Column('fallback_mode', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_config_project_id'), ['project_id'], unique=True)

    op.create_table('ai_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_provider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_provider_project_id'), ['project_id'], unique=False)

    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('primary_language', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('group_chat_id', sa.String(length=80), nullable=True),
    sa.Column('announcement_chat_id', sa.String(length=80), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('moderation_enabled', sa.Boolean(), nullable=False),
    sa.Column('scheduled_content_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_group_chat_id'), ['group_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_project_id'), ['project_id'], unique=False)

    op.create_table('content_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('system_template', sa.Boolean(), nullable=False),
    sa.Column('data_sources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_template_project_id'), ['project_id'], unique=False)

    op.create_table('integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('integration_type', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('secret_enc', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_project_id'), ['project_id'], unique=False)

    op.create_table('knowledge_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_document_project_id'), ['project_id'], unique=False)

    op.create_table('moderation_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderation_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderation_rule_project_id'), ['project_id'], unique=False)

    op.create_table('content_automation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('local_time', sa.String(length=5), nullable=True),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('community_ids', sa.JSON(), nullable=False),
    sa.Column('translate', sa.Boolean(), nullable=False),
    sa.Column('last_run_keys', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['content_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_automation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_automation_project_id'), ['project_id'], unique=False)

    op.create_table('conversation_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=160), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_event_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_event_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_event_telegram_user_id'), ['telegram_user_id'], unique=False)

    op.create_table('escalation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('source_user', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('destination', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalation_project_id'), ['project_id'], unique=False)

    op.create_table('knowledge_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_document.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunk_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunk_project_id'), ['project_id'], unique=False)

    op.create_table('post_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('automation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('telegram_message_id', sa.String(length=80), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['content_automation.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_history_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_history_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_history_project_id'))
        batch_op.drop_index(batch_op.f('ix_post_history_community_id'))

    op.drop_table('post_history')
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunk_project_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunk_document_id'))

    op.drop_table('knowledge_chunk')
    with op.batch_alter_table('escalation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalation_project_id'))

    op.drop_table('escalation')
    with op.batch_alter_table('conversation_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_event_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_event_project_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_conversation_event_community_id'))

    op.drop_table('conversation_event')
    with op.batch_alter_table('content_automation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_automation_project_id'))

    op.drop_table('content_automation')
    with op.batch_alter_table('moderation_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_rule_project_id'))

    op.drop_table('moderation_rule')
    with op.batch_alter_table('knowledge_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_document_project_id'))

    op.drop_table('knowledge_document')
    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_project_id'))

    op.drop_table('integration')
    with op.batch_alter_table('content_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_template_project_id'))

    op.drop_table('content_template')
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_project_id'))
        batch_op.drop_index(batch_op.f('ix_community_group_chat_id'))

    op.drop_table('community')
    with op.batch_alter_table('ai_provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_provider_project_id'))

    op.drop_table('ai_provider')
    with op.batch_alter_table('agent_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_config_project_id'))

    op.drop_table('agent_config')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_organisation_id'))

    op.drop_table('project')
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_user_id'))
        batch_op.drop_index(batch_op.f('ix_membership_organisation_id'))

    op.drop_table('membership')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organisation_slug'))

    op.drop_table('organisation')
    # ### end Alembic commands ###
